Make getCustomerCards() return the same type of object in all places
proseLA/authorizenet_cim pull request #50
Opened 2021-04-16 12:15 UTC by scottcwilson

2021-04-16 12:25 UTC, scottcwilson commented
Sample log from version 2.2.3

[demo.log](https://github.com/proseLA/authorizenet_cim/files/6325000/demo.log)

2021-04-20 15:50 UTC, proseLA requested changes
scott,
i do not like the naming.  i would prefer to leave method getCustomerCards in the _cim class unchanged;  i think the new method getCustomerCardList should be the one that returns the array, and we can add that also into the _cim class.

then we can remove all of it from the _cof class.

we would then need to change the calls on the admin observer and in the modules card update.

does that make sense?

2021-04-20 15:50 UTC, proseLA commented on includes/modules/payment/authorizenet_cim.php
> +   	    $cards_on_file =  parent::getCustomerCardList($customerID, $all);
we are in _cim here.  parent would be base.  i think this line is incorrect.

2021-04-20 15:53 UTC, proseLA commented
the demo log does not make sense to me.  let me look at the history a bit.

2021-04-20 18:54 UTC, scottcwilson commented
Let's close this for now.  You had fixed the issue I was seeing in a more recent version of the software, so these changes don't really make sense - but you may want to consider the change in `admin/includes/classes/observers/class.cim_admin_observer.php`.

2021-04-20 18:54 UTC, closed without merging

2021-04-21 01:55 UTC, proseLA commented
yeah.  in the future please open an issue as opposed to doing the work on a PR.  the more i am now looking at this PR, the more problems i am seeing.  there were different elements to the array in _cim `getCreditCards` than in the fields of the object of resultQuery...  and your `!empty` in the template file was set the wrong way.

there is a lot of lines of code here, and at some point i hope to be able to refactor it and make it cleaner, but there are very few people using it; and my affiliate link for auth.net nets me $7.50/month.  barely enough to get extra cheese on my whopper!  

i'm going to do a small refactor as i agree with you on the original point; i have the same method name in different classes which returned different object types.  and i do not like that at all.  despite it working fine.

best.

best.

2021-04-21 11:02 UTC, scottcwilson commented
Very good.  Thanks for the review!